[Details]
  Icon = "fyne.png"
  Name = "desktop"
  ID = "top.langenius.app"
  Version = "0.0.3"
  Build = 4

[Development]
  HelperText = "This binary was built with debug symbols"

[Release]
  HelperText = "This binary was built without debug symbols"

[LinuxAndBSD]
  GenericName = "Toolkit Demo"
  Categories = ["Development"]
  Comment = "A demo of Fyne and its capabilities."
  Keywords = ["demo", "fyne"]
